services:
  db:
    image: mariadb:latest
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./.devcontainer/data/mariadb/data:/var/lib/mysql:cached


  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: unless-stopped

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./.devcontainer/data/nginx/www/html:/var/www/html
      - ./.devcontainer/data/nginx/etc/default.conf:/etc/nginx/default.conf


